# Generated by Django 5.0.1 on 2026-04-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('Memo', 'Memo'), ('Letter', 'Letter'), ('Report', 'Report')], default='Memo', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='receiver',
            field=models.CharField(default='', help_text='Document receiver', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='sender',
            field=models.CharField(default='', help_text='Document sender', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
