# Generated by Django 5.0.1 on 2026-04-09 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_description_document_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.CharField(choices=[('General', 'General'), ('Registrar', 'Registrar'), ('Dean Office', 'Dean Office'), ('Guidance Office', 'Guidance Office'), ('Accounting', 'Accounting'), ('Library', 'Library')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='document_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='reference_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='DocumentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated'), ('Deleted', 'Deleted'), ('Looked Up', 'Looked Up')], max_length=50)),
                ('message', models.TextField()),
                ('previous_status', models.CharField(blank=True, default='', max_length=50)),
                ('new_status', models.CharField(blank=True, default='', max_length=50)),
                ('changed_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
